name: Push stats

on:
  schedule:
    - cron: "20 * * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install package
        run: yarn
      - name: Push repo stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          COLLECTION_PATH: ./stats-data
          REPO: AdguardTeam/AdguardFilters
        run: ./bin/github-push.js
